//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManager.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IReportManagerService")]
    public interface IReportManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport1", ReplyAction="http://tempuri.org/IReportManagerService/getReport1Response")]
        string getReport1(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport1", ReplyAction="http://tempuri.org/IReportManagerService/getReport1Response")]
        System.Threading.Tasks.Task<string> getReport1Async(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport2", ReplyAction="http://tempuri.org/IReportManagerService/getReport2Response")]
        string getReport2(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport2", ReplyAction="http://tempuri.org/IReportManagerService/getReport2Response")]
        System.Threading.Tasks.Task<string> getReport2Async(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport3", ReplyAction="http://tempuri.org/IReportManagerService/getReport3Response")]
        string getReport3(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport3", ReplyAction="http://tempuri.org/IReportManagerService/getReport3Response")]
        System.Threading.Tasks.Task<string> getReport3Async(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport4", ReplyAction="http://tempuri.org/IReportManagerService/getReport4Response")]
        string getReport4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport4", ReplyAction="http://tempuri.org/IReportManagerService/getReport4Response")]
        System.Threading.Tasks.Task<string> getReport4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport5", ReplyAction="http://tempuri.org/IReportManagerService/getReport5Response")]
        string getReport5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport5", ReplyAction="http://tempuri.org/IReportManagerService/getReport5Response")]
        System.Threading.Tasks.Task<string> getReport5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport6", ReplyAction="http://tempuri.org/IReportManagerService/getReport6Response")]
        string getReport6(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/getReport6", ReplyAction="http://tempuri.org/IReportManagerService/getReport6Response")]
        System.Threading.Tasks.Task<string> getReport6Async(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportManagerServiceChannel : ReportManager.ServiceReference.IReportManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportManagerServiceClient : System.ServiceModel.ClientBase<ReportManager.ServiceReference.IReportManagerService>, ReportManager.ServiceReference.IReportManagerService {
        
        public ReportManagerServiceClient() {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getReport1(System.DateTime start, System.DateTime end) {
            return base.Channel.getReport1(start, end);
        }
        
        public System.Threading.Tasks.Task<string> getReport1Async(System.DateTime start, System.DateTime end) {
            return base.Channel.getReport1Async(start, end);
        }
        
        public string getReport2(int priority) {
            return base.Channel.getReport2(priority);
        }
        
        public System.Threading.Tasks.Task<string> getReport2Async(int priority) {
            return base.Channel.getReport2Async(priority);
        }
        
        public string getReport3(System.DateTime start, System.DateTime end) {
            return base.Channel.getReport3(start, end);
        }
        
        public System.Threading.Tasks.Task<string> getReport3Async(System.DateTime start, System.DateTime end) {
            return base.Channel.getReport3Async(start, end);
        }
        
        public string getReport4() {
            return base.Channel.getReport4();
        }
        
        public System.Threading.Tasks.Task<string> getReport4Async() {
            return base.Channel.getReport4Async();
        }
        
        public string getReport5() {
            return base.Channel.getReport5();
        }
        
        public System.Threading.Tasks.Task<string> getReport5Async() {
            return base.Channel.getReport5Async();
        }
        
        public string getReport6(string id) {
            return base.Channel.getReport6(id);
        }
        
        public System.Threading.Tasks.Task<string> getReport6Async(string id) {
            return base.Channel.getReport6Async(id);
        }
    }
}
