//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRealTimeUnitService")]
    public interface IRealTimeUnitService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/pubInit")]
        void pubInit(string keyPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/pubInit")]
        System.Threading.Tasks.Task pubInitAsync(string keyPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/sendData")]
        void sendData(string address, string datastr, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/sendData")]
        System.Threading.Tasks.Task sendDataAsync(string address, string datastr, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitServiceChannel : RealTimeUnit.ServiceReference.IRealTimeUnitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitServiceClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference.IRealTimeUnitService>, RealTimeUnit.ServiceReference.IRealTimeUnitService {
        
        public RealTimeUnitServiceClient() {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void pubInit(string keyPath) {
            base.Channel.pubInit(keyPath);
        }
        
        public System.Threading.Tasks.Task pubInitAsync(string keyPath) {
            return base.Channel.pubInitAsync(keyPath);
        }
        
        public void sendData(string address, string datastr, byte[] signature) {
            base.Channel.sendData(address, datastr, signature);
        }
        
        public System.Threading.Tasks.Task sendDataAsync(string address, string datastr, byte[] signature) {
            return base.Channel.sendDataAsync(address, datastr, signature);
        }
    }
}
